### ISSUE TITLE
Access cuckoo web portal from PC outside of the host machine

### ISSUE THREAD

**Issue by veanome** [nbeede/BoomBox#2]
Hello, is there a way I access the cuckoo web portal via my PC that's on a different subnet? I want to pass through the Host Machine and open the cuckoo web portal on my PC instead of having to remote into the host machine and opening it up there.

My PC (10.10.10.10) ---> Host Machine (10.20.20.20)---> Cuckoo VM (Web Portal) (192.168.30.100)

Any help would be great! Thanks!

**Comment by nodauf** [comment]
Hi,
If your Host Machine is reachable from your PC, you should add a new route on your PC like 192.168.30.0/24 gw 10.20.20.20
