### ISSUE TITLE
TLS Error Powershell 1.0 install_choco.ps1

### ISSUE THREAD

**Issue by Ethnical** [nbeede/BoomBox#4]
Hi there,
TLS 1.0 it's used by default using powershell.. 
We need to add this line in **install_choco.ps1** to use TLS1.2 and avoid the SSL error.
**[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12**
Thanks you for you work btw !

**Comment by nbeede** [comment]
Closing with PR merge 😃
